# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
        exclude: '^tsconfig.json$'
      - id: pretty-format-json
        args: ["--autofix"]
        exclude: '^tsconfig.json$'
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.5.0
    hooks:
      - id: eslint
        args: ["--fix"]
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [ file ]
        additional_dependencies:
          - typescript
          - eslint
          - eslint-config-prettier
          - eslint-config-standard
          - eslint-plugin-import
          - eslint-plugin-node
          - eslint-plugin-prettier
          - eslint-plugin-promise
          - eslint-plugin-simple-import-sort
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
